version: "3.9"
services:
  database_postgres:
    image: postgis/postgis
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
